apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: fix-the-volume-permission1
        image: busybox
        command:
        - sh
        - -c
        - |
           mkdir -p /opt/sonarqube/data/es8 
           chown -R 1000:1000 /opt/sonarqube/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
      containers:
        - name: sonarqube
          image: sonarqube:latest
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://postgres:5432/sonarqube"
            - name: SONAR_JDBC_USERNAME
              value: "sonarqube"
            - name: SONAR_JDBC_PASSWORD
              value: "sonarqube"
          volumeMounts:
            - mountPath: "/opt/sonarqube/data"
              name: sonarqube-data
            - mountPath: "/opt/sonarqube/logs"
              name: sonarqube-logs
      securityContext:
        fsGroup: 1000
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-pvc
        - name: sonarqube-logs
          emptyDir: {}