apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
      name: jenkins
    - name: jenkins-agent
      port: 50000  # Port for inbound agents
      targetPort: 50000